DM-41126: Use PS1 for astrometry in cosmos_pdr2
lsst/ap_verify_ci_cosmos_pdr2 pull request #39
Opened 2023-10-10 20:26 UTC by parejkoj

2023-10-11 22:45 UTC, kfindeisen approved these changes
Assuming we'll never want to use Gaia here again, can you please remove those refcats from `preloaded/` and its registry? It'll make things cleaner and avoid surprises in the future.

2023-10-11 22:48 UTC, kfindeisen requested changes
Oh, actually there is one mandatory change: please update the Readme, Sphinx docs, and `scripts/generate_refcats_gen3.py` to reflect the lack of Gaia usage. The PR template should have mentioned that (opened as [DM-41163](https://jira.lsstcorp.org/browse/DM-41163)).

I'd also recommend keeping `config/calibrateImage.py` in sync with `calibrate.py`, but I assume you were planning to do that on DM-40387 anyway.

2023-10-25 18:29 UTC, parejkoj commented
I've removed the gaia dr2 files (if HSC does switch to gaia, they'd use DR3 since we have that now), and all references to them that I could find, including the preloaded registry (exact commands used are in the relevant commit).

I also used this opportunity to trim out the unnecessary skymap tracts and patches. See the sqlite commands used in the relevant commit.

I have the fix to the calibrateImage config on the DM-40387 branch, which has been reviewed.

2023-10-28 00:26 UTC, kfindeisen approved these changes
Looks good, just some non-retroactive gripes about doing things properly.

2023-10-28 00:26 UTC, kfindeisen commented on README.md
> sqlite3 preloaded/gen3.sqlite3 'vacuum;'

I'm pretty sure it's bad practice to muck around with the registry as part of Butler ops, but I suppose it did no harm in this case.

2023-10-28 00:26 UTC, kfindeisen commented on config/export.yaml
These commits aren't quite self-contained: most of these changes should have been on "Drastically reduce..." (and it would have helped visualize what that commit is actually doing!)

2023-10-28 00:39 UTC, parejkoj commented on README.md
I agree, but this was the quickest and easiest way I could think of to strip out those extra tracts and patches. It would have been best to create the database without them in the first place. I hope we have notes for that in the template?

2023-10-28 00:42 UTC, parejkoj commented on README.md
Oops, my previous comment was incorrect: I thought your comment was in reference to the other commit. In this case, I did the manual `vacuum` in the hopes that it would cut the database size even more, but it only did by a few kB. Since the goal here is to have a small test repo, it should be fine. I'll ask in middleware-support though, to see what they think about periodic dust-bunny cleanup with a `vacuum`.

2023-10-28 00:44 UTC, parejkoj commented on config/export.yaml
I don't think so? That commit did exactly one thing: strip out the unnecessary tracts and patches. That's what made the sqlite file so huge. The commit to remove the Gaia files and DB references was after that, so that I wasn't working with a giant file at that point.

2023-10-30 21:09 UTC, merged